### ISSUE TITLE
Unknown exception with solveWithMILP True.

### ISSUE THREAD

**Issue by tagomaru** [NeuralNetworkVerification/Marabou#398]
I got the unknown exception with solveWithMILP True.

### simple_model2.nnet:
```
// simple_model 
2,2,3,3,
2,2,3,
0,
-100000.0,-100000.0,
100000.0,100000.0,
0.0,0.0,0.0,
1.0,1.0,1.0,
1.0,1.0,
-1.0,-1.0,
0.0,
0.0,
2.0,1.0,
1.0,1.0,
1.0,1.0,
0.0,
100.0,
0.0,
```

### max.py:
```
from maraboupy import Marabou as marabou
nnet_file_name = "work/simple_model2.nnet"
net = marabou.read_nnet(nnet_file_name)
net.addMaxConstraint(set(net.outputVars[0]), net.outputVars[0][2])
options = marabou.createOptions(solveWithMILP=True)
vals, stats = net.solve(options=options)
```

### Error:
```
$ python3 max.py
(removed)
Traceback (most recent call last):
  File "max.py", line 21, in <module>
    vals, stats = net.solve(options=options)
  File "/Users/XXX/Documents/work/Marabou/maraboupy/MarabouNetwork.py", line 263, in solve
    vals, stats = MarabouCore.solve(ipq, options, filename)
RuntimeError: Caught an unknown exception!
```

### No error with solveWithMILP False:
I changed True to False of solveWithMILP on max.py
```
$ python3 max.py
(removed)
unsat
```

**Comment by AleksandarZeljic** [comment]
Hi @tagomaru, is this still an issue?

**Comment by tagomaru** [comment]
Hi @AleksandarZeljic 
No, it seemed to be fixed.
I am going to close this...
