### ISSUE TITLE
Build with Gurobi fails

### ISSUE THREAD

**Issue by Reginhar** [NeuralNetworkVerification/Marabou#454]
Hello,

When I try to build Marabou with the Gurobi option on Ubuntu by following the README, I get errors when it runs the tests. I first installed Gurobi 9.1.2, fixed the compatibility issue, added the required lines to .bashrc and started a new shell. I verified that the Gurobi executables are on my PATH. I also tried Gurobi 9.1.1, but I got the same errors.

Does anyone know how I could fix this?

```
cmake .. -DENABLE_GUROBI=ON
cmake --build . -j 8
```

Showing only the test output:

 ```
Scanning dependencies of target build-tests
Test project /mnt/c/Users/ReinierJ/Documents/mybuildtmp/Marabou/build
      Start  1: Test_AbsoluteValueConstraint
      Start  2: Test_BlandsRule
      Start  3: Test_BoundManager
      Start  4: Test_ConstraintBoundTightener
      Start  5: Test_ConstraintMatrixAnalyzer
      Start  6: Test_CostFunctionManager
      Start  7: Test_DantzigsRule
      Start  8: Test_DegradationChecker
 1/60 Test  #2: Test_BlandsRule ...................   Passed    0.21 sec
      Start  9: Test_DisjunctionConstraint
 2/60 Test  #3: Test_BoundManager .................   Passed    0.23 sec
      Start 10: Test_DnCWorker
 3/60 Test  #4: Test_ConstraintBoundTightener .....   Passed    0.24 sec
      Start 11: Test_Engine
 4/60 Test  #5: Test_ConstraintMatrixAnalyzer .....   Passed    0.26 sec
      Start 12: Test_InputQuery
 5/60 Test  #6: Test_CostFunctionManager ..........   Passed    0.27 sec
      Start 13: Test_LargestIntervalDivider
 6/60 Test  #7: Test_DantzigsRule .................   Passed    0.23 sec
      Start 14: Test_MaxConstraint
 7/60 Test  #1: Test_AbsoluteValueConstraint ......   Passed    0.41 sec
      Start 15: Test_MILPEncoder
 8/60 Test  #9: Test_DisjunctionConstraint ........   Passed    0.15 sec
      Start 16: Test_PolarityBasedDivider
 9/60 Test #10: Test_DnCWorker ....................   Passed    0.30 sec
      Start 17: Test_Preprocessor
10/60 Test  #8: Test_DegradationChecker ...........   Passed    0.39 sec
      Start 18: Test_ProjectedSteepestEdge
11/60 Test #13: Test_LargestIntervalDivider .......   Passed    0.18 sec
      Start 19: Test_ReluConstraint
12/60 Test #12: Test_InputQuery ...................   Passed    0.38 sec
      Start 20: Test_RowBoundTightener
13/60 Test #11: Test_Engine .......................   Passed    0.51 sec
      Start 21: Test_SignConstraint
14/60 Test #18: Test_ProjectedSteepestEdge ........   Passed    0.24 sec
      Start 22: Test_SmtCore
15/60 Test #14: Test_MaxConstraint ................   Passed    0.50 sec
      Start 23: Test_Tableau
16/60 Test #20: Test_RowBoundTightener ............   Passed    0.23 sec
      Start 24: Test_CSRMatrix
17/60 Test #15: Test_MILPEncoder ..................Child aborted***Exception:   0.55 sec
Running 1 testterminate called after throwing an instance of 'GRBException'

      Start 25: Test_CompareFactorizations
18/60 Test #16: Test_PolarityBasedDivider .........   Passed    0.50 sec
      Start 26: Test_ForrestTomlinFactorization
19/60 Test #17: Test_Preprocessor .................   Passed    0.54 sec
      Start 27: Test_LUFactorization
20/60 Test #19: Test_ReluConstraint ...............   Passed    0.50 sec
      Start 28: Test_LUFactors
21/60 Test #23: Test_Tableau ......................   Passed    0.28 sec
      Start 29: Test_PermutationMatrix
22/60 Test #24: Test_CSRMatrix ....................   Passed    0.28 sec
      Start 30: Test_SparseFTFactorization
23/60 Test #25: Test_CompareFactorizations ........   Passed    0.27 sec
      Start 31: Test_SparseGaussianEliminator
24/60 Test #21: Test_SignConstraint ...............   Passed    0.49 sec
      Start 32: Test_SparseLUFactorization
25/60 Test #26: Test_ForrestTomlinFactorization ...   Passed    0.23 sec
      Start 33: Test_SparseLUFactors
26/60 Test #22: Test_SmtCore ......................   Passed    0.54 sec
      Start 34: Test_SparseUnsortedArray
27/60 Test #27: Test_LUFactorization ..............   Passed    0.29 sec
      Start 35: Test_SparseUnsortedArrays
28/60 Test #28: Test_LUFactors ....................   Passed    0.23 sec
      Start 36: Test_SparseUnsortedList
29/60 Test #29: Test_PermutationMatrix ............   Passed    0.19 sec
      Start 37: Test_SparseUnsortedLists
30/60 Test #30: Test_SparseFTFactorization ........   Passed    0.28 sec
      Start 38: Test_ConstSimpleData
31/60 Test #31: Test_SparseGaussianEliminator .....   Passed    0.27 sec
      Start 39: Test_Error
32/60 Test #32: Test_SparseLUFactorization ........   Passed    0.27 sec
      Start 40: Test_File
33/60 Test #33: Test_SparseLUFactors ..............   Passed    0.27 sec
      Start 41: Test_FloatUtils
34/60 Test #34: Test_SparseUnsortedArray ..........   Passed    0.27 sec
      Start 42: Test_GurobiWrapper
35/60 Test #35: Test_SparseUnsortedArrays .........   Passed    0.24 sec
      Start 43: Test_HashMap
36/60 Test #36: Test_SparseUnsortedList ...........   Passed    0.20 sec
      Start 44: Test_HashSet
37/60 Test #37: Test_SparseUnsortedLists ..........   Passed    0.17 sec
      Start 45: Test_HeapData
38/60 Test #38: Test_ConstSimpleData ..............   Passed    0.27 sec
      Start 46: Test_List
39/60 Test #39: Test_Error ........................   Passed    0.24 sec
      Start 47: Test_MString
40/60 Test #40: Test_File .........................   Passed    0.20 sec
      Start 48: Test_MStringf
41/60 Test #41: Test_FloatUtils ...................   Passed    0.17 sec
      Start 49: Test_Map
42/60 Test #43: Test_HashMap ......................   Passed    0.25 sec
      Start 50: Test_Pair
43/60 Test #44: Test_HashSet ......................   Passed    0.26 sec
      Start 51: Test_Queue
44/60 Test #45: Test_HeapData .....................   Passed    0.27 sec
      Start 52: Test_Set
45/60 Test #46: Test_List .........................   Passed    0.28 sec
      Start 53: Test_Stack
46/60 Test #47: Test_MString ......................   Passed    0.23 sec
      Start 54: Test_Vector
47/60 Test #48: Test_MStringf .....................   Passed    0.19 sec
      Start 55: Test_MatrixMultiplication
48/60 Test #49: Test_Map ..........................   Passed    0.28 sec
      Start 65: Test_QueryLoader
49/60 Test #50: Test_Pair .........................   Passed    0.24 sec
      Start 66: Test_DeepPolyAnalysis
50/60 Test #51: Test_Queue ........................   Passed    0.20 sec
      Start 67: Test_NetworkLevelReasoner
51/60 Test #42: Test_GurobiWrapper ................***Failed    0.69 sec
Running 1 test
In GurobiWrapperTestSuite::test_optimize:
/mnt/c/Users/ReinierJ/Documents/mybuildtmp/Marabou/src/common/tests/Test_GurobiWrapper.h:39: Error: Test failed: Exception thrown from test
Failed 1 of 1 test
Success rate: 0%

=================================================================
==16125==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 36768 byte(s) in 1 object(s) allocated from:
    #0 0x7f75e95e5dc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7f75e721415b in GRBemptyenvadv (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6c615b)

Indirect leak of 20952 byte(s) in 1 object(s) allocated from:
    #0 0x7f75e95e5bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f75e7214e2b in GRBemptyenvadv (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6c6e2b)

Indirect leak of 11968 byte(s) in 374 object(s) allocated from:
    #0 0x7f75e95e5bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f75e720bb96 in PRIVATE0000000000770f82 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6bdb96)

Indirect leak of 8662 byte(s) in 374 object(s) allocated from:
    #0 0x7f75e95e5bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f75e720bbcb in PRIVATE0000000000770f82 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6bdbcb)

Indirect leak of 8080 byte(s) in 1 object(s) allocated from:
    #0 0x7f75e95e5dc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7f75e720b9ad in PRIVATE0000000000770cd8 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6bd9ad)

Indirect leak of 1600 byte(s) in 1 object(s) allocated from:
    #0 0x7f75e95e5bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f75e723a128 in PRIVATE000000000079b424 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6ec128)

Indirect leak of 521 byte(s) in 1 object(s) allocated from:
    #0 0x7f75e95e5bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f75e72142f4 in GRBemptyenvadv (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6c62f4)

Indirect leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7f75e95e5dc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7f75e721432b in GRBemptyenvadv (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6c632b)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f75e95e5bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f75e720b972 in PRIVATE0000000000770cd8 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6bd972)

Indirect leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x7f75e95e5bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f75e71dd932 in PRIVATE000000000073fec5 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x68f932)

SUMMARY: AddressSanitizer: 88649 byte(s) leaked in 756 allocation(s).

      Start 68: Test_WsLayerElimination
52/60 Test #52: Test_Set ..........................   Passed    0.35 sec
      Start 69: Test_ParallelSolver
53/60 Test #53: Test_Stack ........................   Passed    0.36 sec
54/60 Test #54: Test_Vector .......................   Passed    0.33 sec
55/60 Test #55: Test_MatrixMultiplication .........   Passed    0.30 sec
56/60 Test #65: Test_QueryLoader ..................   Passed    0.38 sec
57/60 Test #66: Test_DeepPolyAnalysis .............   Passed    0.44 sec
58/60 Test #68: Test_WsLayerElimination ...........   Passed    0.39 sec
59/60 Test #67: Test_NetworkLevelReasoner .........   Passed    0.47 sec
60/60 Test #69: Test_ParallelSolver ...............***Failed    0.73 sec
Running 2 tests
In NetworkLevelReasonerTestSuite::test_enqueueSolver:
/mnt/c/Users/ReinierJ/Documents/mybuildtmp/Marabou/src/nlr/tests/Test_ParallelSolver.h:39: Error: Test failed: Exception thrown from test
In NetworkLevelReasonerTestSuite::test_clear_solver_queue:
/mnt/c/Users/ReinierJ/Documents/mybuildtmp/Marabou/src/nlr/tests/Test_ParallelSolver.h:54: Error: Test failed: Exception thrown from test
Failed 2 of 2 tests
Success rate: 0%

=================================================================
==16160==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 73536 byte(s) in 2 object(s) allocated from:
    #0 0x7fc572eafdc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7fc570ade15b in GRBemptyenvadv (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6c615b)

Indirect leak of 41904 byte(s) in 2 object(s) allocated from:
    #0 0x7fc572eafbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fc570adee2b in GRBemptyenvadv (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6c6e2b)

Indirect leak of 23936 byte(s) in 748 object(s) allocated from:
    #0 0x7fc572eafbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fc570ad5b96 in PRIVATE0000000000770f82 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6bdb96)

Indirect leak of 17324 byte(s) in 748 object(s) allocated from:
    #0 0x7fc572eafbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fc570ad5bcb in PRIVATE0000000000770f82 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6bdbcb)

Indirect leak of 16160 byte(s) in 2 object(s) allocated from:
    #0 0x7fc572eafdc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7fc570ad59ad in PRIVATE0000000000770cd8 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6bd9ad)

Indirect leak of 3200 byte(s) in 2 object(s) allocated from:
    #0 0x7fc572eafbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fc570b04128 in PRIVATE000000000079b424 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6ec128)

Indirect leak of 1042 byte(s) in 2 object(s) allocated from:
    #0 0x7fc572eafbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fc570ade2f4 in GRBemptyenvadv (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6c62f4)

Indirect leak of 96 byte(s) in 2 object(s) allocated from:
    #0 0x7fc572eafdc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7fc570ade32b in GRBemptyenvadv (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6c632b)

Indirect leak of 80 byte(s) in 2 object(s) allocated from:
    #0 0x7fc572eafbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fc570ad5972 in PRIVATE0000000000770cd8 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x6bd972)

Indirect leak of 20 byte(s) in 2 object(s) allocated from:
    #0 0x7fc572eafbc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7fc570aa7932 in PRIVATE000000000073fec5 (/opt/gurobi912/linux64/lib/libgurobi91.so+0x68f932)

SUMMARY: AddressSanitizer: 177298 byte(s) leaked in 1512 allocation(s).


95% tests passed, 3 tests failed out of 60

Label Time Summary:
basis_factorization unit       =   3.45 sec*proc (14 tests)
common unit                    =   5.11 sec*proc (18 tests)
engine unit                    =   8.11 sec*proc (23 tests)
network_level_reasoner unit    =   2.02 sec*proc (4 tests)
query_loader unit              =   0.38 sec*proc (1 test)

Total Test time (real) =   3.40 sec

The following tests FAILED:
         15 - Test_MILPEncoder (Child aborted)
         42 - Test_GurobiWrapper (Failed)
         69 - Test_ParallelSolver (Failed)
Errors while running CTest
make[2]: *** [CMakeFiles/build-tests.dir/build.make:57: build-tests] Error 8
make[1]: *** [CMakeFiles/Makefile2:708: CMakeFiles/build-tests.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

**Comment by AleksandarZeljic** [comment]
Hi, can you ensure that you have an up-to-date Gurobi licence on that machine?

**Comment by AleksandarZeljic** [comment]
Closing due to lack of activity.
