### ISSUE TITLE
Operation Sub not implemented

### ISSUE THREAD

**Issue by lambdaxdotx** [NeuralNetworkVerification/Marabou#609]
Hello,

I am running the `master` version of Marabou:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.
$ git pull
Already up to date.
```
The `runMarabou.py` on ACAS-Xu network and property _already_ provided by Marabou outputs this error:
```
$ ./resources/runMarabou.py --marabou-binary build/Marabou resources/onnx/acasxu/ACASXU_experimental_v2a_1_1.onnx resources/properties/acas_property_1.txt
Traceback (most recent call last):
  File "./resources/runMarabou.py", line 165, in <module>
    main()
  File "./resources/runMarabou.py", line 29, in main
    query, network = createQuery(args)
  File "./resources/runMarabou.py", line 63, in createQuery
    network = Marabou.read_onnx(networkPath)
  File "../maraboupy/Marabou.py", line 75, in read_onnx
    return MarabouNetworkONNX(filename, inputNames, outputNames, reindexOutputVars=reindexOutputVars)
  File "../maraboupy/MarabouNetworkONNX.py", line 40, in __init__
    self.readONNX(filename, inputNames, outputNames, reindexOutputVars=reindexOutputVars)
  File "../maraboupy/MarabouNetworkONNX.py", line 107, in readONNX
    self.processGraph()
  File "../maraboupy/MarabouNetworkONNX.py", line 144, in processGraph
    self.makeGraphEquations(outputName, True)
  File "../maraboupy/MarabouNetworkONNX.py", line 169, in makeGraphEquations
    self.makeGraphEquations(inNodeName, makeEquations)
  File "../maraboupy/MarabouNetworkONNX.py", line 169, in makeGraphEquations
    self.makeGraphEquations(inNodeName, makeEquations)
  File "../maraboupy/MarabouNetworkONNX.py", line 169, in makeGraphEquations
    self.makeGraphEquations(inNodeName, makeEquations)
  [Previous line repeated 18 more times]
  File "../maraboupy/MarabouNetworkONNX.py", line 177, in makeGraphEquations
    self.makeMarabouEquations(nodeName, makeEquations)
  File "../maraboupy/MarabouNetworkONNX.py", line 227, in makeMarabouEquations
    raise NotImplementedError("Operation {} not implemented".format(node.op_type))
NotImplementedError: Operation Sub not implemented
```

Since I am using a network and property found in Marabou repo (under `resources/`), I guess this should work.

Is this a known issue?

**Comment by lambdaxdotx** [comment]
I found out that @MatthewDaggitt has done some work on the subject. Maybe Matthew knows more about this?

**Comment by MatthewDaggitt** [comment]
I'm sorry, I only worked on the C++ Onnx interface not the Python one. Unfortunately they're not unified at the moment. (I think the Python one should use the C++ one to avoid having to develop all the features and bug fixes twice...)

**Comment by idan0610** [comment]
Operation Sub is now implemented in the python interface of ONNX
