### ISSUE TITLE
KeyError: '/Constant_output_0'

### ISSUE THREAD

**Issue by lydialin1212** [NeuralNetworkVerification/Marabou#655]
Hi, 

I am verifying with ONNX format. Marabou shows "KeyError: '/Constant_output_0'" when I use  "torch.add(tensor, constant)". But when I change the constant to a tensor, this error will not happen. Please take a look. Look forward to any response!

The log is 
```
File "/home/xxx/Marabou/resources/../maraboupy/MarabouNetworkONNX.py", line 961, in addEquations
shape2 = self.shapeMap[inputName2]
KeyError: '/Constant_output_0
```

The model is as follows
```
class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.net = torch.nn.Sequential(
            torch.nn.Linear(30, 32),
            torch.nn.Linear(32, 16),
            torch.nn.Linear(16, 1),
            torch.nn.Tanh()
        )

    def forward(self, features):
        y = self.net(features)
        y = torch.add(y, 1)
        return y
```

**Comment by yizhake** [comment]
I encounter a similar error with a bit different code.

My network is implemented as follows:
```
class Net(nn.Module):
    def __init__(self, orig_net):
        super(Net, self).__init__()
        self.model = nn.Sequential(
            *orig_net.layers[:len(orig_net.layers)],
            orig_net.classifiers[-1]
        )

    def forward(self, x):
        cum_sum = 0.0
        for layer in self.model[:-1]:
            x = layer(x)
            cum_sum += x
        return self.model[-1](cum_sum)
```
and the error i get after converting to onnx and trying to convert to torch with MarabouOnnxParser (of maraboupy) is:
```
Traceback (most recent call last):
  File "verify/with_marabou.py", line 57, in <module>
    mnet = read_onnx_by_marabou(onet)
  File "verify/with_marabou.py", line 23, in read_onnx_by_marabou
    network = Marabou.read_onnx([tmp_onnx_file.name](http://tmp_onnx_file.name/))
  File "Marabou/maraboupy/Marabou.py", line 75, in read_onnx
    return MarabouNetworkONNX(filename, inputNames, outputNames, reindexOutputVars=reindexOutputVars)
  File "Marabou/maraboupy/MarabouNetworkONNX.py", line 41, in __init__
    self.readONNX(filename, inputNames, outputNames, reindexOutputVars=reindexOutputVars)
  File "Marabou/maraboupy/MarabouNetworkONNX.py", line 108, in readONNX
    self.processGraph()
  File "Marabou/maraboupy/MarabouNetworkONNX.py", line 145, in processGraph
    self.makeGraphEquations(outputName, True)
  File "Marabou/maraboupy/MarabouNetworkONNX.py", line 170, in makeGraphEquations
    self.makeGraphEquations(inNodeName, makeEquations)
  File "Marabou/maraboupy/MarabouNetworkONNX.py", line 178, in makeGraphEquations
    self.makeMarabouEquations(nodeName, makeEquations)
  File "Marabou/maraboupy/MarabouNetworkONNX.py", line 222, in makeMarabouEquations
    self.addEquations(node, makeEquations)
  File "Marabou/maraboupy/MarabouNetworkONNX.py", line 957, in addEquations
    shape2 = self.shapeMap[inputName2]
KeyError: '/Constant_output_0'
```

Thanks.

**Comment by wu-haoze** [comment]
The issue is with not updating shapeMap when handling constant node. @yizhake I created this PR that fixes the issue seen on the network you sent.
