### ISSUE TITLE
AssertionError: assert v < self.numVars

### ISSUE THREAD

**Issue by dongfeicui** [NeuralNetworkVerification/Marabou#671]
[**code:**](https://github.com/NeuralNetworkVerification/Marabou/blob/master/maraboupy/MarabouNetwork.py#L241C40-L241C40)
`
for e in self.equList:
            eq = MarabouCore.Equation(e.EquationType) 
            for (c, v) in e.addendList:
                assert v < self.numVars
                eq.addAddend(c, v)
            eq.setScalar(e.scalar)
            ipq.addEquation(eq)
`

**error information:**

/home/johann/miniconda3/envs/py3.7/bin/python /home/johann/Projects/Marabou/maraboupy/examples/2_ONNXExample.py 
2023-09-02 15:11:23.001720: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
WARNING:tensorflow:From /home/johann/miniconda3/envs/py3.7/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

Convolutional Network Example
Check query with less restrictive output constraint (Should be SAT)
Traceback (most recent call last):
  File "/home/johann/Projects/Marabou/maraboupy/examples/2_ONNXExample.py", line 96, in &lt;module&gt;
    exitCode, vals, stats = network.solve(options=options)
  File "/home/johann/Projects/Marabou/maraboupy/MarabouNetwork.py", line 304, in solve
    ipq = self.getMarabouQuery()
  File "/home/johann/Projects/Marabou/maraboupy/MarabouNetwork.py", line 242, in getMarabouQuery
    assert v < self.numVars
AssertionError

**Comment by wu-haoze** [comment]
@dongfeicui  Thanks for bring this issue to my attention. This is because the example is outdated. Please checkout the example in this PR(#673) .

**Comment by dongfeicui** [comment]
Thanks! However, I still get the error.
`
              Convolutional Network Example
              Check query with less restrictive output constraint (Should be SAT)
              Traceback (most recent call last):
                File "/home/johann/Projects/Marabou/maraboupy/examples/onnx_test.py", line 90, in <module>
                  exitCode, vals, stats = network.solve(options = options)
                File "/home/johann/Projects/Marabou/maraboupy/MarabouNetwork.py", line 301, in solve
                  ipq = self.getMarabouQuery()
                File "/home/johann/Projects/Marabou/maraboupy/MarabouNetwork.py", line 242, in getMarabouQuery
                  eq.addAddend(c, v)
              TypeError: addAddend(): incompatible function arguments. The following argument types are supported:
                  1. (self: maraboupy.MarabouCore.Equation, arg0: float, arg1: int) -> None
              
              Invoked with: <maraboupy.MarabouCore.Equation object at 0x7f7cb7d64730>, array([[[[0.11868373, 0.07181699, 0.1593607 , ..., 0.12088654,
          0.05278583, 0.08719786],
         [0.08405102, 0.04493088, 0.05681298, ..., 0.22245388,
          0.1852215 , 0.15450351],
         [0.17534618, 0.13060756, 0.01761406, ..., 0.10236487,
          0.05296735, 0.0487432 ],
         ...,
         [0.05961502, 0.09761831, 0.09729563, ..., 0.08716526,
          0.07265161, 0.07043408],
         [0.06158127, 0.10802538, 0.07126066, ..., 0.03404454,
          0.09472602, 0.05604867],
         [0.05869861, 0.10690148, 0.11083344, ..., 0.05455628,
          0.0718229 , 0.0377076 ]]],


       [[[0.07592764, 0.17358328, 0.05072777, ..., 0.12204338,
          0.29659262, 0.16630885],
         [0.18683001, 0.04641113, 0.12104554, ..., 0.1161211 ,
          0.12925343, 0.16653049],
         [0.13614446, 0.04882334, 0.13168497, ..., 0.17925936,
          0.06499259, 0.10899444],
         ...,
         [0.074344  , 0.06931169, 0.0622032 , ..., 0.10510846,
          0.07967949, 0.0901242 ],
         [0.10280828, 0.12569591, 0.09766634, ..., 0.11105043,
          0.12155933, 0.09068184],
         [0.05816609, 0.12807287, 0.10949545, ..., 0.1185562 ,
          0.06776981, 0.07586801]]],


       [[[0.11249637, 0.05554269, 0.17602299, ..., 0.09051538,
          0.04328481, 0.07409234],
         [0.12245758, 0.08770888, 0.09259319, ..., 0.0963508 ,
          0.11627837, 0.1009678 ],
         [0.0764182 , 0.09214474, 0.1837028 , ..., 0.12197733,
          0.16710745, 0.12431081],
         ...,
         [0.07796451, 0.07519329, 0.10017172, ..., 0.0716019 ,
          0.09532272, 0.10435976],
         [0.09675623, 0.06662193, 0.09912696, ..., 0.0972626 ,
          0.07031327, 0.09199685],
         [0.09151326, 0.07154955, 0.10453591, ..., 0.07917297,
          0.06534111, 0.0742232 ]]],


       ...,


       [[[0.05711139, 0.12414922, 0.16848595, ..., 0.06877242,
          0.11211475, 0.03261003],
         [0.03940973, 0.07402248, 0.04304283, ..., 0.08852854,
          0.10305092, 0.14645638],
         [0.1769776 , 0.0565651 , 0.07433166, ..., 0.04069878,
          0.07533292, 0.04184926],
         ...,
         [0.09150818, 0.08864387, 0.08037427, ..., 0.13349514,
          0.03785631, 0.0891608 ],
         [0.09566166, 0.11703134, 0.07934329, ..., 0.15784125,
          0.1091188 , 0.07776611],
         [0.06760743, 0.07966295, 0.1215471 , ..., 0.10790461,
          0.09868034, 0.07515934]]],


       [[[0.10781573, 0.06878354, 0.11229729, ..., 0.10027946,
          0.08104488, 0.06143349],
         [0.10177509, 0.10079858, 0.1274803 , ..., 0.09583003,
          0.06416576, 0.08345239],
         [0.09495731, 0.07837318, 0.07325035, ..., 0.09484068,
          0.11266906, 0.08805591],
         ...,
         [0.07630502, 0.07863118, 0.12475732, ..., 0.09610514,
          0.08865626, 0.09671853],
         [0.08621745, 0.07368686, 0.0895911 , ..., 0.04571458,
          0.12958305, 0.11039808],
         [0.1015411 , 0.1511232 , 0.10151795, ..., 0.07996842,
          0.11994647, 0.06750471]]],


       [[[0.04529685, 0.03663752, 0.15849395, ..., 0.10244921,
          0.06178164, 0.0458424 ],
         [0.03255338, 0.13129182, 0.06497331, ..., 0.05906438,
          0.02808665, 0.06634798],
         [0.07539173, 0.05302418, 0.14557958, ..., 0.03653239,
          0.17527552, 0.05974127],
         ...,
         [0.17510073, 0.15320413, 0.08234213, ..., 0.05589401,
          0.06661592, 0.10763092],
         [0.13965747, 0.09254649, 0.11086534, ..., 0.10934415,
          0.0774427 , 0.1091056 ],
         [0.09533136, 0.04181939, 0.14729734, ..., 0.1206825 ,
          0.13000071, 0.03162175]]]], dtype=float32), -0.3137557948594843
`

**Comment by dongfeicui** [comment]
Heartfelt Thanks for your reply!
I'm currently importing the[CondGauss](https://github.com/eclerico/CondGauss) neural network into Marabou.
This is my neural network [onnx file](https://github.com/NeuralNetworkVerification/Marabou/files/12577446/state_dict.zip) that you need to unzip it. Also,I have implemented some new operators in the [MarabouNetworkONNX.py file](https://github.com/NeuralNetworkVerification/Marabou/files/12577589/MarabouNetworkONNX.zip).
I've also made some modifications to the internal code of existing operators, primarily concerning the distinction between variables and constants. Like this

![image](https://github.com/NeuralNetworkVerification/Marabou/assets/60336738/45ea6b59-2805-421a-8296-6502f3be96e2)


```
 test_onnx.py 

from maraboupy import Marabou
  import numpy as np
  

  # Set the Marabou option to restrict printing
  options = Marabou.createOptions(verbosity = 0)
  

  # Convolutional neural network example
  # ------------------------------------
  #
  # Network maps 8x16 grayscale images two values
  print("\nConvolutional Network Example")
  # filename = '../../resources/onnx/KJ_TinyTaxiNet.onnx'
  filename = '../../resources/onnx/state_dict.onnx'
  network = Marabou.read_onnx(filename)
  

  # Get the input and output variable numbers; [0] since first dimension is batch size
  inputVars = network.inputVars[0][0]
  outputVars = network.outputVars[0][0]
  

  # Setup a local robustness query
  delta = 0.03
  for h in range(inputVars.shape[0]):
      for w in range(inputVars.shape[1]):
          network.setLowerBound(inputVars[h][w][0], 0.5-delta)
          network.setUpperBound(inputVars[h][w][0], 0.5+delta)
  

  # Set output bounds
  network.setLowerBound(outputVars[0], 6.0)
  

  # Call to Marabou solver (should be SAT)
  print("Check query with less restrictive output constraint (Should be SAT)")
  exitCode, vals, stats = network.solve(options = options)
  assert( exitCode == "sat")
  assert len(vals) &gt; 0
  

  # Set more restrictive output bounds
  network.setLowerBound(outputVars[0], 7.0)
  
  # Call to Marabou solver (should be UNSAT)
  print("Check query with more restrictive output constraint (Should be UNSAT)")
  exitCode, vals, stats = network.solve(options = options)
  assert( exitCode == "unsat")
  assert len(vals) == 0
```

**Comment by wu-haoze** [comment]
Hi @dongfeicui , I see. It might be that your extension breaks the internal assumptions. Looking at the onnx file shared, it seems that the second and third inputs to the conv operations are constant. Maybe it's simplier to create a modified onnx file that does not contain the new operations.

<img width="665" alt="Screenshot 2023-09-11 at 16 56 11" src="https://github.com/NeuralNetworkVerification/Marabou/assets/10719979/540d2ba3-751d-485d-bf69-197ac038e243">

**Comment by dongfeicui** [comment]
Thanks for your reply! So you think the problem is that we use new operators. So if we don't use the new operator, can we give conv the second and third inputs. These two inputs should specify the weight and bias of conv
