### ISSUE TITLE
"cannot find reference 'MarabouCore' in '__init__.py'" after cmake MacOS12.5 python>3.8

### ISSUE THREAD

**Issue by INPUTrrr0** [NeuralNetworkVerification/Marabou#761]
I am unable to install marabou on my current machine. I am able to go through the commands up until "cmake --build ." where I meet the following error: 
<img width="1473" alt="1791708139337_ pic copy"  src="https://github.com/NeuralNetworkVerification/Marabou/assets/44755971/176c76b2-694a-4314-9992-cfced532d3b5">

I am using cmake version 3.28.3 on Apple M1 Pro MacOS 12.5.1. 

Attempt of using "pip install maraboupy" results in "ERROR: Could not find a version that satisfies the requirement maraboupy (from versions: none)
ERROR: No matching distribution found for maraboupy".

Attempt to build from wheel results in: "ERROR: maraboupy-1.0.0-cp39-cp39-macosx_13_0_arm64.whl is not a supported wheel on this platform."

I've tried both python3.9 and python3.11. 

Update: doing pip install in a new conda environment seems to work: "Requirement already satisfied: maraboupy in /opt/anaconda3/envs/nap/lib/python3.11/site-packages (1.0.0)" but `>>> from maraboupy import Marabou` has the error: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/maraboupy/Marabou.py", line 17, in <module>
    from maraboupy.MarabouCore import *
ModuleNotFoundError: No module named 'maraboupy.MarabouCore'. 

So I'm still not able to get it to work.

**Comment by MatthewDaggitt** [comment]
Hi @INPUTrrr0, you were very unlucky hitting that first bug when you built from source. It was only active for about 8 hours on the repo. If you pull and try running `cmake` again it should work?

> Attempt of using "pip install maraboupy" results in "ERROR: Could not find a version that satisfies the requirement maraboupy (from versions: none)
ERROR: No matching distribution found for maraboupy".

As for this one, I'm afraid I'm not an expert on the Python building side of things, but can you give us your OS and your architecture? Maybe @wenkokke can help out?

**Comment by INPUTrrr0** [comment]
Thank you @MatthewDaggitt, I'm trying to run cmake again. 

As for pip, I'm able to perform "pip install marabou" on a conda env where I'm using "/opt/anaconda3/envs/nap/lib/python3.11" and I verified that marabou has these files: "/opt/anaconda3/envs/nap/bin/Marabou
/opt/anaconda3/envs/nap/lib/python3.11/site-packages/maraboupy-1.0.0.dist-info/*
/opt/anaconda3/envs/nap/lib/python3.11/site-packages/maraboupy/*". 
Using this python3.11, I am able to import and use other packages such as numpy, but when I add the line "from maraboupy import Marabou", my terminal outputs: "zsh: illegal hardware instruction python3 scratch.py" (scratch.py is where I added the import line of code). My MacOS is 12.5 with M1 Pro. 
Thanks again!

**Comment by wenkokke** [comment]
The issue is that there simply are no arm64 binaries for macOS <13.

There was no GitHub support for macOS arm64 builds, so the macOS arm64 binaries were built on my personal machine, which runs macOS 13.

**Comment by wenkokke** [comment]
It's possible to build macOS arm64 wheels for macOS >=11 using GitHub Actuons _now_, but that would require a PR and a new version release, which would likely take a very long time.

**Comment by INPUTrrr0** [comment]
Thanks @wenkokke for your reply! I was able to run cmake and add the binary to my conda environment. However, I am met with this error: <img width="614" alt="Screen Shot 2024-02-18 at 13 11 10" src="https://github.com/NeuralNetworkVerification/Marabou/assets/44755971/e989393a-33eb-4dba-8ff3-1f9798aac0a8">
Is this a result of that one failed unit test? Thanks!

**Comment by wenkokke** [comment]
Not sure if there's any differences, but to be safe it's probably best to build from source using pip rather than directly calling CMake, e.g., by calling `pip install .`.

**Comment by wu-haoze** [comment]
Closing due to inactivity. Feel free to reopen.
