### ISSUE TITLE
GRBException

### ISSUE THREAD

**Issue by ggustavs** [NeuralNetworkVerification/Marabou#817]
Hello! I am trying to run a simple query generated by Vehicle, but I ran into GRBException. I have uploaded the model and query [bug.zip](https://github.com/user-attachments/files/15957295/bug.zip). 

The node that ran this query has 128 GB ram. 
The query was ran in a singularity image made from a docker image of ubuntu.

The full error output:

Running on cn8:
Network: /home/gus/reproducers/full_tutorial_model.onnx
Property: /home/gus/reproducers/vcl_cache/robust0-query1.txt

Engine::processInputQuery: Input query (before preprocessing): 18827 equations, 41818 variables
Engine::processInputQuery: Input query (after preprocessing): 48613 equations, 55631 variables

Input bounds:
        x0: [  0.0000,   0.0039]
        x1: [  0.0000,   0.0039]
        x2: [  0.0000,   0.0039]
        x3: [  0.0000,   0.0039]
        x4: [  0.0000,   0.0039]
        x5: [  0.0000,   0.0039]
        x6: [  0.0000,   0.0039]
        x7: [  0.0000,   0.0039]
        x8: [  0.0000,   0.0039]
        x9: [  0.0000,   0.0039]
        x10: [  0.0000,   0.0039]
        x11: [  0.0000,   0.0039]
        x12: [  0.0000,   0.0039]
        x13: [  0.0000,   0.0039]
        x14: [  0.0000,   0.0039]
        x15: [  0.0000,   0.0039]
        x16: [  0.0000,   0.0039]
        x17: [  0.0000,   0.0039]
        x18: [  0.0000,   0.0039]
        x19: [  0.0000,   0.0039]
        x20: [  0.0000,   0.0039]
        x21: [  0.0000,   0.0039]
        x22: [  0.0000,   0.0039]
        x23: [  0.0000,   0.0039]
        x24: [  0.0000,   0.0039]
        x25: [  0.0000,   0.0039]
        x26: [  0.0000,   0.0039]
        x27: [  0.0000,   0.0039]
        x28: [  0.0000,   0.0039]
        x29: [  0.0000,   0.0039]
        x30: [  0.0000,   0.0039]
        x31: [  0.0000,   0.0039]
        x32: [  0.0000,   0.0039]
        x33: [  0.0000,   0.0039]
        x34: [  0.0000,   0.0039]
        x35: [  0.0000,   0.0039]
        x36: [  0.0000,   0.0039]
        x37: [  0.0000,   0.0039]
        x38: [  0.0000,   0.0039]
        x39: [  0.0000,   0.0039]
        x40: [  0.0000,   0.0039]
        x41: [  0.0000,   0.0039]
        x42: [  0.0000,   0.0039]
        x43: [  0.0000,   0.0039]
        x44: [  0.0000,   0.0039]
        x45: [  0.0000,   0.0039]
        x46: [  0.0000,   0.0039]
        x47: [  0.0000,   0.0039]
        x48: [  0.0000,   0.0039]
        x49: [  0.0000,   0.0039]
        x50: [  0.0000,   0.0039]
        x51: [  0.0000,   0.0039]
        x52: [  0.0000,   0.0039]
        x53: [  0.0000,   0.0039]
        x54: [  0.0000,   0.0039]
        x55: [  0.0000,   0.0039]
        x56: [  0.0000,   0.0039]
        x57: [  0.0000,   0.0039]
        x58: [  0.0000,   0.0039]
        x59: [  0.0000,   0.0039]
        x60: [  0.0000,   0.0039]
        x61: [  0.0000,   0.0039]
        x62: [  0.0000,   0.0039]
        x63: [  0.0000,   0.0039]
        x64: [  0.0000,   0.0039]
        x65: [  0.0000,   0.0039]
        x66: [  0.0000,   0.0039]
        x67: [  0.0000,   0.0039]
        x68: [  0.0000,   0.0039]
        x69: [  0.0000,   0.0039]
        x70: [  0.0000,   0.0039]
        x71: [  0.1373,   0.1412]
        x72: [  0.1608,   0.1647]
        x73: [  0.2824,   0.2863]
        x74: [  0.1725,   0.1765]
        x75: [  0.2392,   0.2431]
        x76: [  0.1569,   0.1608]
        x77: [  0.0000,   0.0039]
        x78: [  0.0000,   0.0039]
        x79: [  0.0000,   0.0039]
        x80: [  0.0000,   0.0039]
        x81: [  0.0000,   0.0039]
        x82: [  0.0000,   0.0039]
        x83: [  0.0000,   0.0039]
        x84: [  0.0000,   0.0039]
        x85: [  0.0000,   0.0039]
        x86: [  0.2275,   0.2314]
        x87: [  0.3882,   0.3922]
        x88: [  0.6588,   0.6627]
        x89: [  0.6510,   0.6549]
        x90: [  0.6902,   0.6941]
        x91: [  0.7098,   0.7137]
        x92: [  0.7137,   0.7176]
        x93: [  0.7137,   0.7176]
        x94: [  0.7020,   0.7059]
        x95: [  0.7490,   0.7529]
        x96: [  0.7529,   0.7608]
        x97: [  0.8627,   0.8667]
        x98: [  0.8667,   0.8706]
        x99: [  0.9529,   0.9608]
        x100: [  0.9490,   0.9569]
        x101: [  0.9647,   0.9686]
        x102: [  0.9490,   0.9529]
        x103: [  0.9333,   0.9412]
        x104: [  0.9255,   0.9333]
        x105: [  0.8706,   0.8745]
        x106: [  0.7843,   0.7882]
        x107: [  0.2588,   0.2627]
        x108: [  0.0000,   0.0039]
        x109: [ -0.0039,   0.0039]
        x110: [ -0.0039,   0.0039]
        x111: [  0.0078,   0.0118]
        x112: [  0.0000,   0.0039]
        x113: [  0.6667,   0.6706]
        x114: [  0.8471,   0.8510]
        x115: [  0.7529,   0.7569]
        x116: [  0.7608,   0.7647]
        x117: [  0.7373,   0.7412]
        x118: [  0.7373,   0.7412]
        x119: [  0.8275,   0.8314]
        x120: [  0.8235,   0.8275]
        x121: [  0.8235,   0.8275]
        x122: [  0.8196,   0.8235]
        x123: [  0.8000,   0.8039]
        x124: [  0.7725,   0.7804]
        x125: [  0.7569,   0.7608]
        x126: [  0.7333,   0.7412]
        x127: [  0.7373,   0.7451]
        x128: [  0.7333,   0.7412]
        x129: [  0.7216,   0.7294]
        x130: [  0.7059,   0.7137]
        x131: [  0.6863,   0.6902]
        x132: [  0.6745,   0.6784]
        x133: [  0.6863,   0.6902]
        x134: [  0.7451,   0.7529]
        x135: [  0.8275,   0.8353]
        x136: [  0.7373,   0.7451]
        x137: [  0.2902,   0.2941]
        x138: [  0.0000,   0.0039]
        x139: [ -0.0039,   0.0039]
        x140: [  0.3608,   0.3647]
        x141: [  0.8235,   0.8275]
        x142: [  0.6941,   0.6980]
        x143: [  0.6549,   0.6588]
        x144: [  0.6118,   0.6157]
        x145: [  0.6902,   0.6941]
        x146: [  0.7529,   0.7569]
        x147: [  0.7765,   0.7804]
        x148: [  0.7490,   0.7529]
        x149: [  0.7647,   0.7686]
        x150: [  0.7490,   0.7529]
        x151: [  0.7608,   0.7647]
        x152: [  0.7647,   0.7725]
        x153: [  0.7843,   0.7882]
        x154: [  0.8196,   0.8275]
        x155: [  0.8235,   0.8314]
        x156: [  0.8078,   0.8157]
        x157: [  0.8314,   0.8392]
        x158: [  0.8196,   0.8275]
        x159: [  0.7961,   0.8039]
        x160: [  0.7647,   0.7725]
        x161: [  0.7176,   0.7216]
        x162: [  0.6706,   0.6745]
        x163: [  0.7020,   0.7059]
        x164: [  0.7569,   0.7608]
        x165: [  0.8549,   0.8627]
        x166: [  0.4745,   0.4824]
        x167: [  0.0000,   0.0039]
        x168: [  0.4510,   0.4549]
        x169: [  0.8078,   0.8118]
        x170: [  0.8039,   0.8078]
        x171: [  0.7098,   0.7137]
        x172: [  0.6745,   0.6784]
        x173: [  0.6941,   0.6980]
        x174: [  0.7098,   0.7137]
        x175: [  0.7294,   0.7333]
        x176: [  0.8078,   0.8118]
        x177: [  0.7804,   0.7843]
        x178: [  0.8471,   0.8510]
        x179: [  0.8824,   0.8863]
        x180: [  0.9255,   0.9294]
        x181: [  0.8627,   0.8667]
        x182: [  0.8627,   0.8706]
        x183: [  0.8549,   0.8627]
        x184: [  0.8353,   0.8431]
        x185: [  0.7882,   0.7961]
        x186: [  0.7490,   0.7569]
        x187: [  0.7569,   0.7647]
        x188: [  0.7412,   0.7490]
        x189: [  0.7216,   0.7294]
        x190: [  0.7686,   0.7765]
        x191: [  0.8314,   0.8392]
        x192: [  0.7569,   0.7647]
        x193: [  0.7137,   0.7216]
        x194: [  0.7922,   0.8000]
        x195: [  0.1843,   0.1922]
        x196: [  0.2627,   0.2667]
        x197: [  0.9020,   0.9059]
        x198: [  0.8667,   0.8706]
        x199: [  0.8627,   0.8667]
        x200: [  0.8706,   0.8745]
        x201: [  0.8196,   0.8235]
        x202: [  0.8314,   0.8353]
        x203: [  0.8549,   0.8588]
        x204: [  0.8745,   0.8784]
        x205: [  0.9373,   0.9412]
        x206: [  0.9608,   0.9647]
        x207: [  0.8863,   0.8941]
        x208: [  0.7647,   0.7686]
        x209: [  0.9373,   0.9451]
        x210: [  0.8314,   0.8392]
        x211: [  0.7725,   0.7804]
        x212: [  0.8039,   0.8118]
        x213: [  0.7686,   0.7765]
        x214: [  0.7216,   0.7294]
        x215: [  0.8431,   0.8510]
        x216: [  0.8784,   0.8863]
        x217: [  0.8235,   0.8314]
        x218: [  0.8000,   0.8078]
        x219: [  0.7529,   0.7608]
        x220: [  0.7961,   0.8039]
        x221: [  0.8275,   0.8353]
        x222: [  0.7961,   0.8039]
        x223: [  0.2902,   0.2980]
        x224: [  0.1137,   0.1176]
        x225: [  0.8980,   0.9020]
        x226: [  0.8784,   0.8824]
        x227: [  0.8745,   0.8784]
        x228: [  0.8745,   0.8784]
        x229: [  0.8510,   0.8549]
        x230: [  0.8431,   0.8471]
        x231: [  0.8667,   0.8706]
        x232: [  0.8588,   0.8627]
        x233: [  0.6549,   0.6627]
        x234: [  0.4549,   0.4627]
        x235: [  0.4118,   0.4196]
        x236: [  0.2863,   0.2902]
        x237: [  0.2510,   0.2588]
        x238: [  0.9412,   0.9490]
        x239: [  0.8471,   0.8549]
        x240: [  0.8392,   0.8471]
        x241: [  0.7569,   0.7647]
        x242: [  0.8588,   0.8667]
        x243: [  0.9725,   0.9804]
        x244: [  0.9137,   0.9216]
        x245: [  0.8941,   0.9020]
        x246: [  0.8941,   0.9020]
        x247: [  0.8667,   0.8745]
        x248: [  0.8196,   0.8275]
        x249: [  0.7725,   0.7804]
        x250: [  0.9098,   0.9176]
        x251: [  0.3843,   0.3882]
        x252: [  0.0000,   0.0039]
        x253: [  0.8824,   0.8863]
        x254: [  0.8941,   0.8980]
        x255: [  0.8706,   0.8745]
        x256: [  0.8196,   0.8235]
        x257: [  0.8000,   0.8039]
        x258: [  0.8235,   0.8275]
        x259: [  0.7490,   0.7529]
        x260: [  0.6039,   0.6078]
        x261: [  0.7373,   0.7412]
        x262: [  0.8667,   0.8706]
        x263: [  0.8980,   0.9020]
        x264: [  1.0000,   1.0039]
        x265: [  0.5843,   0.5922]
        x266: [  0.3098,   0.3176]
        x267: [  0.9373,   0.9451]
        x268: [  0.8588,   0.8667]
        x269: [  0.8000,   0.8078]
        x270: [  0.8000,   0.8078]
        x271: [  0.8000,   0.8078]
        x272: [  0.8353,   0.8431]
        x273: [  0.8235,   0.8314]
        x274: [  0.8235,   0.8314]
        x275: [  0.8627,   0.8706]
        x276: [  0.8745,   0.8824]
        x277: [  0.8902,   0.8980]
        x278: [  0.7882,   0.7961]
        x279: [  0.0118,   0.0157]
        x280: [  0.0000,   0.0039]
        x281: [  0.9647,   0.9686]
        x282: [  0.9098,   0.9137]
        x283: [  0.8627,   0.8667]
        x284: [  0.8275,   0.8314]
        x285: [  0.8667,   0.8706]
        x286: [  0.9176,   0.9216]
        x287: [  0.8667,   0.8706]
        x288: [  1.0000,   1.0039]
        x289: [  1.0000,   1.0039]
        x290: [  0.8745,   0.8784]
        x291: [  0.8078,   0.8118]
        x292: [  0.7569,   0.7608]
        x293: [  0.9569,   0.9647]
        x294: [  0.6196,   0.6275]
        x295: [  0.7804,   0.7882]
        x296: [  0.8157,   0.8235]
        x297: [  0.8118,   0.8196]
        x298: [  0.8353,   0.8431]
        x299: [  0.7961,   0.8039]
        x300: [  0.8118,   0.8196]
        x301: [  0.8745,   0.8824]
        x302: [  0.8627,   0.8706]
        x303: [  0.8745,   0.8824]
        x304: [  0.8118,   0.8196]
        x305: [  0.7294,   0.7373]
        x306: [  0.2196,   0.2275]
        x307: [  0.0000,   0.0039]
        x308: [  0.0000,   0.0039]
        x309: [  0.8431,   0.8471]
        x310: [  0.9333,   0.9373]
        x311: [  0.9137,   0.9176]
        x312: [  0.9725,   0.9765]
        x313: [  0.9804,   0.9843]
        x314: [  0.7373,   0.7412]
        x315: [  0.6902,   0.6941]
        x316: [  0.9176,   0.9216]
        x317: [  0.8745,   0.8824]
        x318: [  0.8980,   0.9059]
        x319: [  0.8275,   0.8314]
        x320: [  0.8000,   0.8078]
        x321: [  0.7804,   0.7882]
        x322: [  0.8824,   0.8902]
        x323: [  0.8471,   0.8549]
        x324: [  0.8667,   0.8745]
        x325: [  0.8588,   0.8667]
        x326: [  0.8902,   0.8980]
        x327: [  0.7373,   0.7451]
        x328: [  0.4157,   0.4235]
        x329: [  0.3176,   0.3255]
        x330: [  0.1686,   0.1765]
        x331: [  0.0667,   0.0745]
        x332: [ -0.0039,   0.0039]
        x333: [ -0.0039,   0.0039]
        x334: [ -0.0039,   0.0039]
        x335: [ -0.0039,   0.0039]
        x336: [  0.0000,   0.0039]
        x337: [  0.6235,   0.6275]
        x338: [  0.9569,   0.9608]
        x339: [  0.8784,   0.8824]
        x340: [  0.8431,   0.8471]
        x341: [  0.8588,   0.8627]
        x342: [  0.8745,   0.8784]
        x343: [  0.8784,   0.8824]
        x344: [  0.8549,   0.8588]
        x345: [  0.8275,   0.8314]
        x346: [  0.8118,   0.8196]
        x347: [  0.8549,   0.8588]
        x348: [  0.8627,   0.8706]
        x349: [  0.8314,   0.8392]
        x350: [  0.8078,   0.8157]
        x351: [  0.8902,   0.8980]
        x352: [  0.7961,   0.8039]
        x353: [  0.5647,   0.5725]
        x354: [  0.2392,   0.2471]
        x355: [ -0.0039,   0.0039]
        x356: [ -0.0039,   0.0039]
        x357: [ -0.0039,   0.0039]
        x358: [ -0.0039,   0.0039]
        x359: [ -0.0039,   0.0039]
        x360: [ -0.0039,   0.0039]
        x361: [ -0.0039,   0.0039]
        x362: [  0.0078,   0.0157]
        x363: [ -0.0039,   0.0039]
        x364: [  0.0000,   0.0039]
        x365: [  0.3020,   0.3059]
        x366: [  1.0000,   1.0039]
        x367: [  0.8549,   0.8588]
        x368: [  0.8431,   0.8471]
        x369: [  0.8980,   0.9020]
        x370: [  0.8745,   0.8784]
        x371: [  0.8471,   0.8510]
        x372: [  0.8667,   0.8706]
        x373: [  0.8667,   0.8745]
        x374: [  0.8588,   0.8627]
        x375: [  0.8706,   0.8745]
        x376: [  0.8706,   0.8784]
        x377: [  0.8471,   0.8549]
        x378: [  0.8824,   0.8902]
        x379: [  0.9255,   0.9333]
        x380: [ -0.0039,   0.0039]
        x381: [ -0.0039,   0.0039]
        x382: [ -0.0039,   0.0039]
        x383: [ -0.0039,   0.0039]
        x384: [ -0.0039,   0.0039]
        x385: [  0.0039,   0.0118]
        x386: [  0.0235,   0.0314]
        x387: [  0.0196,   0.0275]
        x388: [  0.0118,   0.0196]
        x389: [ -0.0000,   0.0078]
        x390: [ -0.0039,   0.0039]
        x391: [  0.0000,   0.0039]
        x392: [  0.0000,   0.0039]
        x393: [  0.3608,   0.3647]
        x394: [  0.8157,   0.8235]
        x395: [  0.8471,   0.8549]
        x396: [  0.8471,   0.8549]
        x397: [  0.9137,   0.9216]
        x398: [  0.8706,   0.8784]
        x399: [  0.8549,   0.8588]
        x400: [  0.8353,   0.8392]
        x401: [  0.9098,   0.9137]
        x402: [  0.9412,   0.9451]
        x403: [  0.8941,   0.8980]
        x404: [  0.8980,   0.9059]
        x405: [  0.8902,   0.8980]
        x406: [  0.9216,   0.9294]
        x407: [  0.2118,   0.2196]
        x408: [ -0.0039,   0.0039]
        x409: [ -0.0039,   0.0039]
        x410: [  0.0118,   0.0196]
        x411: [ -0.0039,   0.0039]
        x412: [ -0.0039,   0.0039]
        x413: [ -0.0039,   0.0039]
        x414: [ -0.0039,   0.0039]
        x415: [ -0.0039,   0.0039]
        x416: [ -0.0039,   0.0039]
        x417: [ -0.0039,   0.0000]
        x418: [ -0.0039,   0.0039]
        x419: [  0.0000,   0.0039]
        x420: [  0.2196,   0.2235]
        x421: [  0.6510,   0.6588]
        x422: [  0.4667,   0.4706]
        x423: [  0.9608,   0.9647]
        x424: [  0.8627,   0.8667]
        x425: [  0.8706,   0.8745]
        x426: [  0.8353,   0.8392]
        x427: [  0.8431,   0.8471]
        x428: [  0.8667,   0.8706]
        x429: [  0.7725,   0.7804]
        x430: [  0.7922,   0.8000]
        x431: [  0.8510,   0.8588]
        x432: [  0.8588,   0.8667]
        x433: [  0.8667,   0.8745]
        x434: [  0.9529,   0.9608]
        x435: [  0.3843,   0.3922]
        x436: [ -0.0039,   0.0039]
        x437: [  0.0196,   0.0275]
        x438: [ -0.0039,   0.0039]
        x439: [ -0.0039,   0.0039]
        x440: [ -0.0039,   0.0039]
        x441: [ -0.0039,   0.0039]
        x442: [ -0.0039,   0.0039]
        x443: [ -0.0039,   0.0039]
        x444: [ -0.0039,   0.0039]
        x445: [ -0.0039,   0.0039]
        x446: [ -0.0039,   0.0039]
        x447: [  0.0000,   0.0039]
        x448: [  0.2039,   0.2078]
        x449: [  0.8196,   0.8235]
        x450: [  0.7725,   0.7765]
        x451: [  0.8863,   0.8902]
        x452: [  0.8275,   0.8353]
        x453: [  0.8745,   0.8824]
        x454: [  0.8510,   0.8588]
        x455: [  0.8118,   0.8196]
        x456: [  0.8863,   0.8941]
        x457: [  0.6588,   0.6667]
        x458: [  0.7490,   0.7569]
        x459: [  0.8510,   0.8588]
        x460: [  0.8275,   0.8353]
        x461: [  0.8588,   0.8667]
        x462: [  0.8549,   0.8627]
        x463: [  0.0431,   0.0510]
        x464: [ -0.0039,   0.0039]
        x465: [  0.0078,   0.0157]
        x466: [ -0.0000,   0.0078]
        x467: [ -0.0039,   0.0039]
        x468: [ -0.0039,   0.0039]
        x469: [ -0.0039,   0.0039]
        x470: [ -0.0039,   0.0039]
        x471: [ -0.0039,   0.0039]
        x472: [ -0.0039,   0.0039]
        x473: [ -0.0039,   0.0039]
        x474: [ -0.0039,   0.0039]
        x475: [  0.0000,   0.0039]
        x476: [  0.0000,   0.0039]
        x477: [  0.7882,   0.7961]
        x478: [  0.9490,   0.9569]
        x479: [  0.8588,   0.8667]
        x480: [  0.8706,   0.8784]
        x481: [  0.8314,   0.8392]
        x482: [  0.8235,   0.8314]
        x483: [  0.8196,   0.8275]
        x484: [  0.8275,   0.8353]
        x485: [  0.7020,   0.7098]
        x486: [  0.7725,   0.7804]
        x487: [  0.8314,   0.8392]
        x488: [  0.8510,   0.8588]
        x489: [  0.8902,   0.8980]
        x490: [  0.7529,   0.7608]
        x491: [ -0.0039,   0.0039]
        x492: [ -0.0039,   0.0039]
        x493: [ -0.0039,   0.0039]
        x494: [ -0.0039,   0.0000]
        x495: [ -0.0039,   0.0000]
        x496: [ -0.0039,   0.0039]
        x497: [ -0.0039,   0.0039]
        x498: [ -0.0039,   0.0039]
        x499: [ -0.0039,   0.0039]
        x500: [ -0.0039,   0.0039]
        x501: [ -0.0039,   0.0039]
        x502: [ -0.0039,   0.0039]
        x503: [  0.0000,   0.0039]
        x504: [ -0.0039,   0.0039]
        x505: [  0.6745,   0.6824]
        x506: [  0.9569,   0.9647]
        x507: [  0.8706,   0.8784]
        x508: [  0.8627,   0.8706]
        x509: [  0.8745,   0.8824]
        x510: [  0.8667,   0.8745]
        x511: [  0.8745,   0.8824]
        x512: [  0.8863,   0.8941]
        x513: [  0.9176,   0.9255]
        x514: [  0.8902,   0.8980]
        x515: [  0.8706,   0.8784]
        x516: [  0.8431,   0.8510]
        x517: [  0.8784,   0.8863]
        x518: [  0.7137,   0.7216]
        x519: [ -0.0039,   0.0000]
        x520: [ -0.0039,   0.0039]
        x521: [ -0.0039,   0.0039]
        x522: [ -0.0039,   0.0039]
        x523: [ -0.0039,   0.0039]
        x524: [ -0.0039,   0.0039]
        x525: [ -0.0039,   0.0039]
        x526: [ -0.0039,   0.0039]
        x527: [ -0.0039,   0.0039]
        x528: [ -0.0039,   0.0039]
        x529: [ -0.0039,   0.0039]
        x530: [ -0.0039,   0.0039]
        x531: [  0.0000,   0.0039]
        x532: [ -0.0039,   0.0039]
        x533: [  0.8941,   0.9020]
        x534: [  0.7647,   0.7725]
        x535: [  0.4784,   0.4863]
        x536: [  0.4941,   0.5020]
        x537: [  0.6392,   0.6471]
        x538: [  0.8314,   0.8392]
        x539: [  0.8392,   0.8471]
        x540: [  0.8706,   0.8784]
        x541: [  0.8706,   0.8784]
        x542: [  0.8941,   0.9020]
        x543: [  0.9098,   0.9176]
        x544: [  0.9059,   0.9137]
        x545: [  0.9059,   0.9137]
        x546: [  0.7804,   0.7882]
        x547: [ -0.0039,   0.0039]
        x548: [ -0.0000,   0.0078]
        x549: [ -0.0000,   0.0078]
        x550: [ -0.0000,   0.0078]
        x551: [ -0.0039,   0.0039]
        x552: [ -0.0039,   0.0039]
        x553: [ -0.0039,   0.0039]
        x554: [ -0.0039,   0.0039]
        x555: [ -0.0039,   0.0039]
        x556: [ -0.0039,   0.0039]
        x557: [ -0.0039,terminate called after throwing an instance of 'GRBException'
SIGABRT: abort
PC=0x47cdab m=0 sigcode=0

goroutine 1 [running, locked to thread]:
syscall.RawSyscall(0x3e, 0x3e23c, 0x6, 0x0, 0x0, 0xc000070480, 0xc000070480)
        /usr/lib/golang/src/syscall/asm_linux_amd64.s:78 +0x2b fp=0xc0001afe70 sp=0xc0001afe68 pc=0x47cdab
syscall.Kill(0x3e23c, 0x6, 0x0, 0x0)
        /usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:597 +0x4b fp=0xc0001afeb8 sp=0xc0001afe70 pc=0x479bcb
github.com/sylabs/singularity/internal/app/starter.Master.func2()
        internal/app/starter/master_linux.go:152 +0x61 fp=0xc0001aff00 sp=0xc0001afeb8 pc=0x7928f1
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute.func1()
        internal/pkg/util/mainthread/mainthread.go:21 +0x2f fp=0xc0001aff28 sp=0xc0001aff00 pc=0x790f4f
main.main()
        cmd/starter/main_linux.go:102 +0x5f fp=0xc0001aff60 sp=0xc0001aff28 pc=0x972bbf
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:203 +0x21e fp=0xc0001affe0 sp=0xc0001aff60 pc=0x433b4e
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0001affe8 sp=0xc0001affe0 pc=0x45f7c1

goroutine 6 [syscall]:
os/signal.signal_recv(0xb9da80)
        /usr/lib/golang/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [chan receive]:
github.com/sylabs/singularity/internal/pkg/util/mainthread.Execute(0xc000271c30)
        internal/pkg/util/mainthread/mainthread.go:24 +0xb4
github.com/sylabs/singularity/internal/app/starter.Master(0x7, 0x4, 0x3e24e, 0xc00000eac0)
        internal/app/starter/master_linux.go:151 +0x44c
main.startup()
        cmd/starter/main_linux.go:75 +0x53e
created by main.main
        cmd/starter/main_linux.go:98 +0x35

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x3e23c
rsi    0x6
rbp    0xc0001afea8
rsp    0xc0001afe68
r8     0x0
r9     0x0
r10    0x0
r11    0x202
r12    0xff
r13    0x0
r14    0xb83b64
r15    0x0
rip    0x47cdab
rflags 0x202
cs     0x33
fs     0x0
gs     0x0

**Comment by ggustavs** [comment]
bump?

**Comment by wu-haoze** [comment]
Hum.. I just ran: 
`./Marabou full_tutorial_model.onnx robust0-query1.txt` and it returns a satisfying assignment without issues.

Did you happen to have modified the Gurobi version? There seems to be some backward incompatibility issues with Gurobi so that currently we only support an older version of Gurobi as specified in README.md.

**Comment by ggustavs** [comment]
Hmm, I am running it in a singularity container and the Gurobi version I have used is 9.5.1, same as in the tutorial.
Since it looks like a problem with my installation, I will try rebuilding both Gurobi and Marabou

**Comment by wu-haoze** [comment]
Oh I see. In that case, it might be a problem with the Gurobi license. I haven’t used singularity container, but for virtualbox, you would need to get a license specific for the virtual machine.
