### ISSUE TITLE
Marabou with Gurobi enabled and the Slurm manager

### ISSUE THREAD

**Issue by Dorin-D** [NeuralNetworkVerification/Marabou#824]
Hi,

I am trying to run [VeriX](https://github.com/NeuralNetworkVerification/VeriX), which uses Marabou with Gurobi enabled, on an HPC cluster, using the Slurm job manager. 

1) (works) If I test Marabou with **Gurobi enabled**, in a containerized environment within the interactive session, **without Slurm**, it works fine. 
2) (works) If I test Marabou with **Gurobi disabled**, in the same containerized environment but **within a slurm batch job**, it works fine. 
3) (does not work) If I test Marabou with **Gurobi enabled**, in a containerized environment within a **slurm batch job**, I get an "**Unknown Exception**" when Marabou's solve function is called and it needs to use Gurobi. 

Marabou does not provide much info I can find on this exception, so I will do my best to describe my process so far.

In the absence of root privileges on the remote cluster, I have successfully built Marabou with Gurobi enabled on a Ubuntu (24.04) Docker image on my local machine. I have moved the built Marabou folder onto the remote cluster. I then create a small Dockerfile which allows me to run Marabou.
<details><summary>Dockerfile</summary>
<p>

FROM ubuntu:latest
RUN apt-get update && \
	apt-get install -y apt-utils wget && \
	apt-get install -y cmake build-essential libc6
#probably unnecessary to install miniconda
RUN mkdir -p ~/miniconda3 && \ 
	cd ~/miniconda3
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
RUN bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
RUN rm -rf ~/miniconda3/miniconda.sh
RUN ~/miniconda3/bin/conda init bash

</p>
</details> 

The HPC cluster I am using allows [Singularity](https://apptainer.org/user-docs/master/index.html) instead of Docker, so I convert the docker image into the Singularity .sif format. If I try to execute a script for VeriX in this singularity container, using the built Marabou with Gurobi enabled, on the HPC cluster, in the interactive terminal session, the script works fine.
<details><summary>VeriX test script</summary>
<p>

from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.utils import to_categorical
from keras.datasets import mnist
from keras.losses import CategoricalCrossentropy
from keras.optimizers import Adam
import tf2onnx
from VeriX import *
"""
download and process MNIST data.
"""
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)
x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255
verix = VeriX(dataset="MNIST",
              image=x_test[112],
              model_path="models/mnist-10x2.onnx")
verix.traversal_order(traverse="heuristic")
verix.get_explanation(epsilon=0.05,
                      plot_counterfactual=True)

</p>
</details> 

Next, I want to submit the same script using Slurm. I write a simple batch script to execute the test script in Slurm (in details below):

<details><summary>Slurm batch script</summary>
<p>

#!/usr/bin/env bash

#Specify resource requirements
#SBATCH --time=1:00:00
#SBATCH --partition=cpu
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16G

conda activate verix9

#Setup recording of consumed resources
srun sprofile start

export PYTHONUNBUFFERED=1
#Spawn a task to run the train script.
srun singularity exec ~/docker/maraboudependencies.sif /home/users/ddoncenco/miniconda3/envs/verix9/bin/python test.py 

#Print consumed resources
srun sprofile stop
</p>
</details> 

Note: in Slurm, onnxruntime raises an error as in the next summary, to fix that I set the number of threads for the onnx session as the next code block shows:

```
# set the number of threads for onnxruntime; otherwise, slurm will fail at onnxruntime
        num_threads=1
        self.onnx_options = ort.SessionOptions()
        self.onnx_options.inter_op_num_threads = num_threads
        self.onnx_options.intra_op_num_threads = num_threads
        # initialize the session using the provided onnx options
        self.onnx_session = ort.InferenceSession(model_path, self.onnx_options)
```

<details><summary>onnxruntime error in Slurm</summary>
<p>

2024-07-26 11:07:54.551639850 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 2832038, index: 6, mask: {7, 43, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-07-26 11:07:54.551640360 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 2832037, index: 5, mask: {6, 42, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-07-26 11:07:54.551767354 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 2832040, index: 8, mask: {9, 45, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-07-26 11:07:54.551634513 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 2832036, index: 4, mask: {5, 41, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-07-26 11:07:54.551634168 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 2832035, index: 3, mask: {4, 40, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-07-26 11:07:54.565734486 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 2832052, index: 20, mask: {21, 57, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-07-26 11:07:54.565736883 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 2832039, index: 7, mask: {8, 44, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.

</p>
</details> 

And then I submit this Slurm batch script, and I get the following error:

```
Set parameter WLSAccessID
Set parameter WLSSecret
Set parameter LicenseID to value 2531363
Traceback (most recent call last):
  File "/home/users/ddoncenco/formal_xai/temp_verix/VeriX/test.py", line 25, in <module>
    verix.get_explanation(epsilon=0.05,
  File "/home/users/ddoncenco/formal_xai/temp_verix/VeriX/VeriX.py", line 194, in get_explanation
    exit_code, vals, stats = self.mara_model.solve(options=self.options, verbose=False)
  File "/home/users/ddoncenco/formal_xai/Marabou/maraboupy/MarabouNetwork.py", line 75, in solve
    exitCode, vals, stats = MarabouCore.solve(ipq, options, str(filename))
RuntimeError: Caught an unknown exception!
srun: error: node36: task 0: Exited with exit code 1
```

If I set `verbose=True` in `self.mara_model.solve()`, I get 3928 instances of "unsat" before the Gurobi optimizer is called, and then the exception above is raised. 

I need to use slurm in order to be able to run my jobs on the remote cluster. How can I do that? Let me know if you need any other information related to my setup.

**Comment by wu-haoze** [comment]
Hi @Dorin-D , if you're working with a cluster with multiple nodes, the individual Gurobi license would not work as it is tied to a particular machine. If your institution has access to a institutional license you should probably use that. Otherwise, I think Gurobi also offers a cluster license but I'm not familiar with it.

**Comment by Dorin-D** [comment]
Thank you, that seems to be indeed the case - I will check with my institution and Gurobi on what are the steps to take forward.

For other people coming across this issue in the future, if you have an academic license - make sure you have an active internet connection when using the license. 

I'll close this issue now.
